---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- HomeLab:
    - VMWare:
        - icon: vmware-esxi.png
          href: https://xxxx.taffyhome.local
          description: Type 1 hypervisor.
    - Dockge:
        - icon: dockge.png
          href: http://xxxx.taffyhome.local:5001
          description: Docker Control Plane
    - IDRAC 6:
        - icon: idrac.png
          href: https://xxxx.taffyhome.local
          description: Remote management for R610.
    - IDRAC 7:
        - icon: idrac.png
          href: https://xxxx.taffyhome.local
          description: Remote management for R720.
    - IDRAC 9:
        - icon: idrac.png
          href: https://xxxx.taffyhome.local
          description: Remote management for R740xd.

- Developer:
    - Github:
        - icon: github.png
          href: https://github.com/oceanfabreeze
          description: The complete developer platform.
    - AWS:
        - icon: aws.png
          href: https://aws.amazon.com/
          description: Cloud computing services.
    - Tailscale:
        - icon: tailscale.png
          href: https://login.tailscale.com/
          description: a zero-config, no-fuss VPN
    - Cloudflare:
        - icon: cloudflare.png
          href: https://www.cloudflare.com/
          description: Connect, protect, and build everywhere

- Social:
    - Facebook:
        - icon: facebook.png
          href: https://facebook.com/
          description: Connect with friends and the world around you.
    - Instagram:
        - icon: instagram.png
          href: https://instagram.com/
          description: Capture and share the world's moments.
    - LinkedIn:
        - icon: linkedin.png
          href: https://linkedin.com/
          description: Connect with professionals and grow your network.


- News:
    - Jalopnik:
        - abbr: J
          href: https://jalopnik.com/
          description: The world's greatest car website.
    - Gizmodo:
        - abbr: G
          href: https://gizmodo.com/
          description: The gadget guide.
    - The Verge:
        - abbr: V
          href: https://theverge.com/
          description: The Verge covers the intersection of technology, science, art, and culture.
    - Engadget:
        - abbr: E
          href: https://engadget.com/
          description: Everything new in gadgets and consumer electronics.