# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: TAFLab
description: A simple homepage for TAFLab
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey