services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - NGINX_PORT=80 # optional
      - WEB_APP_PORT=3000 # optional
    volumes:
      - /mnt/.ix-apps/app_data/netbootxyz/config:/config # optional
      - /mnt/.ix-apps/app_data/netbootxyz/assets:/assets # optional
    ports:
      - 3333:3000 # optional, destination should match ${WEB_APP_PORT} variable above.
      - 69:69/udp
      - 8080:80 # optional, destination should match ${NGINX_PORT} variable above.
    restart: unless-stopped