services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - TZ=Etc/UTC
    volumes:
      - /etc/apps/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped