# Automation for VM snapshot creation and deletion after 30 days. (Must install community.vmware using ansible-galaxy and pyvmomi)
# Run ansible-galaxy collection install community.vmware
# Run pip install pyvmomi
# Author = oceanfabreeze
# Version = 0.7 Alpha Release
# Changelog:
# 02/08/2025 (05:43PM EST) - Initial Release
---
- name: Create and manage snapshots for all VMs on ESXi
  hosts: localhost
  vars_files:
    - /etc/ansible/vars/vm-snapshot-vars.yml
  gather_facts: true  # Enable fact gathering to get ansible_date_time
  tasks:
    - name: Gather information about all VMs
      community.vmware.vmware_vm_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        validate_certs: no
      register: vm_facts

    - name: Set datacenter (assuming the first datacenter in the facts)
      set_fact:
        datacenter: "{{ vm_facts.virtual_machines[0].datacenter }}"
      when: vm_facts.virtual_machines | length > 0

    - name: Create snapshots for all VMs
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        name: "{{ item.guest_name }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "/{{ datacenter }}/vm/"
        snapshot_name: "{{ item.guest_name }}_snapshot_{{ ansible_date_time.iso8601 }}"
        description: "Snapshot created by Ansible"
        state: present
      loop: "{{ vm_facts.virtual_machines }}"
      delegate_to: localhost

    - name: Gather snapshot information for all VMs
      community.vmware.vmware_guest_snapshot_info:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        name: "{{ item.guest_name }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "/{{ datacenter }}/vm/"
      loop: "{{ vm_facts.virtual_machines }}"
      delegate_to: localhost
      register: snapshot_facts

    - name: Delete snapshots older than 30 days
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_password }}"
        name: "{{ item.guest_name }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "/{{ datacenter }}/vm/"
        snapshot_name: "{{ snapshot.snapshot_name }}"
        state: absent
      loop: "{{ snapshot_facts.results | selectattr('snapshots', 'defined') | map(attribute='snapshots') | flatten }}"
      when: (ansible_date_time.iso8601 | to_datetime) - (snapshot.create_time | to_datetime) > 30
      delegate_to: localhost
